name: Full-stack CI/CD

on:
  push:
    branches:
    - develop
    - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for React
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Docker image for frontend
        run: |
          cd client
          docker build -t frontend-image:latest .

      - name: Re-tag and push frontend Docker image to GitHub Packages
        run: |
          lowercase_repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag frontend-image:latest ghcr.io/$lowercase_repo_name-frontend-image:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/$lowercase_repo_name-frontend-image:latest

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Docker image for backend
        run: |
          cd server
          docker build -t backend-image:latest .

      - name: Re-tag and push backend Docker image to GitHub Packages
        run: |
          lowercase_repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag backend-image:latest ghcr.io/$lowercase_repo_name-backend-image:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/$lowercase_repo_name-backend-image:latest

